version: 2
jobs:
  build:
    working_directory: /go/src/github.com/brunoksato/go-ecs

    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
            go get -u -v github.com/Masterminds/glide
            glide install
            
      - run: 
          name: Running Unit Tests
          command: go test -v $(glide novendor)

      - run: 
          name: Build
          command: go build

  build_and_deploy:
    machine: true
    steps:
      - checkout

      - run:
          name: Build and Deploy Images to ECS
          command: bash deploy.sh

workflows:
    version: 2
    
    test-and-deploy:
      jobs:
        - build
        - hold:
            type: approval
            requires:
             - build
        - build_and_deploy:
            requires:
             - hold
            filters:
              branches:
                only:
                  - master